name: Tests

on:
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

env:
  BUILD_NUMBER: PR${{ github.event.number }}-job-${{ github.run_number }}-attempt-${{ github.run_attempt }}

jobs:
  lint:
    if: contains(fromJson('["workflow_dispatch"]'), github.event_name) || contains(github.event.pull_request.labels.*.name, 'safe to test')
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container: node:14

    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: lint
        run: npm run lint

  chrome:
    if: contains(fromJson('["workflow_dispatch"]'), github.event_name) || contains(github.event.pull_request.labels.*.name, 'safe to test')
    timeout-minutes: 30
    continue-on-error: true
    runs-on: ubuntu-latest
    container: node:14

    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: run tests
        run: node --max-old-space-size=8192 ./tools/jil/bin/cli.js -f merged -b chrome@* -s -t 85000 --concurrent=20
  firefox:
    if: contains(fromJson('["workflow_dispatch"]'), github.event_name) || contains(github.event.pull_request.labels.*.name, 'safe to test')
    timeout-minutes: 30
    continue-on-error: true
    runs-on: ubuntu-latest
    container: node:14

    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: run tests
        run: node --max-old-space-size=8192 ./tools/jil/bin/cli.js -f merged -b firefox@* -s -t 85000 --concurrent=20
  edge:
    if: contains(fromJson('["workflow_dispatch"]'), github.event_name) || contains(github.event.pull_request.labels.*.name, 'safe to test')
    timeout-minutes: 30
    continue-on-error: true
    runs-on: ubuntu-latest
    container: node:14

    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: run tests
        run: node --max-old-space-size=8192 ./tools/jil/bin/cli.js -f merged -b edge@* -s -t 85000 --concurrent=20
  safari:
    if: contains(fromJson('["workflow_dispatch"]'), github.event_name) || contains(github.event.pull_request.labels.*.name, 'safe to test')
    timeout-minutes: 30
    continue-on-error: true
    runs-on: ubuntu-latest
    container: node:14

    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: run tests
        run: node --max-old-space-size=8192 ./tools/jil/bin/cli.js -f merged -b safari@* -s -t 85000 --concurrent=20
  ios:
    if: contains(fromJson('["workflow_dispatch"]'), github.event_name) || contains(github.event.pull_request.labels.*.name, 'safe to test')
    timeout-minutes: 45
    continue-on-error: true
    runs-on: ubuntu-latest
    container: node:14

    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: run tests
        run: node --max-old-space-size=8192 ./tools/jil/bin/cli.js -f merged -b ios@* -s -t 85000 --concurrent=20
  
  android:
    if: contains(fromJson('["workflow_dispatch"]'), github.event_name) || contains(github.event.pull_request.labels.*.name, 'safe to test')
    timeout-minutes: 30
    continue-on-error: true
    runs-on: ubuntu-latest
    container: node:14

    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: run tests
        run: node --max-old-space-size=8192 ./tools/jil/bin/cli.js -f merged -b android@* -s -t 85000 --concurrent=20
  

  ie:
    if: contains(fromJson('["workflow_dispatch"]'), github.event_name) || contains(github.event.pull_request.labels.*.name, 'safe to test')
    timeout-minutes: 90
    runs-on: ubuntu-latest
    container: node:14

    env:
      NEWRELIC_ENVIRONMENT: ci
      JIL_SAUCE_LABS_USERNAME: ${{ secrets.JIL_SAUCE_LABS_USERNAME }}
      JIL_SAUCE_LABS_ACCESS_KEY: ${{ secrets.JIL_SAUCE_LABS_ACCESS_KEY }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.JIL_NODE_NEW_RELIC_LICENSE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: run tests
        run: node --max-old-space-size=8192 ./tools/jil/bin/cli.js -P -b ie@* -s -t 85000 --concurrent=5
  

  check-failures:
    runs-on: ubuntu-latest
    container: node:14
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') && ${{ !failure() }}  # final check if each needed test either pass or cancelled (special circumstance) and didn't outright fail
    needs: [chrome, firefox, edge, safari, android, ios, ie]
    env:
      NRQL_API_KEY: ${{ secrets.NRQL_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: checkout and build
        uses: ./.github/actions/test-setup

      - name: check failed tests
        run: node --max-old-space-size=8192 ./tools/jil/util/get-failed-tests.js
